name: vulpes_data
description: Lib which contains some extracted data from the game Minecraft
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: "^3.35.7"

dependencies:
  flutter:
    sdk: flutter
